apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: toxiproxy
  namespace: llms-chaos
spec:
  selector:
    matchLabels:
      app: toxiproxy
  template:
    metadata:
      labels:
        app: toxiproxy
    spec:
      containers:
        - name: toxiproxy
          image: ghcr.io/shopify/toxiproxy:2.9.0
          ports:
            - containerPort: 8474
          args: ["-host", "0.0.0.0"]
